<?php
/**
 * TL_ROOT/system/modules/ce_flash/languages/de/default.php 
 * 
 * TYPOlight extension: ce_flash 1.0.0 beta1 
 * English translation file 
 * 
 * Copyright : by Psitrax Websolutions 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Christoph Wiechert (Psi), http://www.psitrax.de 
 * Translator: Jan Miethke 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['ce_lightbox4ward']['0'] = "Lightbox4ward";
$GLOBALS['TL_LANG']['CTE']['ce_lightbox4ward']['1'] = "With the use of Lightbox4ward different elements, such als videos, galleries or articels can be presented in a lightbox.";
 
$GLOBALS['TL_LANG']['tl_layout']['lightbox4ward_error'] = "The Mootools-Template moo_mediabox must not be used with moo_lightbox4ward.";
?>
