<?php
/**
 * TL_ROOT/system/modules/ce_flash/languages/de/default.php 
 * 
 * TYPOlight extension: ce_flash 1.0.0 beta1 
 * Deutsch translation file 
 * 
 * Copyright : by Psitrax Websolutions 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Christoph Wiechert (Psi), http://www.psitrax.de 
 * Translator: Christoph Wiechert (Psi), http://www.psitrax.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['ce_lightbox4ward']['0'] = "Lightbox4ward";
$GLOBALS['TL_LANG']['CTE']['ce_lightbox4ward']['1'] = "Mit der Lightbox4ward können verschiedenste Elemente wie Videos, Galerien oder Artikel in einer Lightbox dargestellt werden.";
 
$GLOBALS['TL_LANG']['tl_layout']['lightbox4ward_error'] = "Das Mootools-Template moo_mediabox kann nicht gleichzeitig mit moo_lightbox4ward verwendet werden.";
?>
